annotations:
  category: Database
apiVersion: v2
dependencies:
  - condition: haproxy.enabled
    name: haproxy
    repository: "file://./charts/haproxy"
    version: "1.18.0"
name: marklogic
description: MarkLogic Server is a multi-model database that has both NoSQL and trusted enterprise data management capabilities.
appVersion: "11.1.0"
type: application
keywords:
  - marklogic
  - database
  - nosql
sources:
  - https://github.com/marklogic/marklogic-kubernetes
  - https://www.marklogic.com/
version: 1.1.2
